development:
  adapter: postgresql
  encoding: unicode
  database: webshop_development
  pool: 5  
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: webshop_test
  pool: 5  
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: webshop_production
  pool: 5  
  password:
